version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000" # port for agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${PROJECT_ROOT_DIR}:/var/jenkins_home/workspace/project
    networks:
      - jenkins_network

  jenkins_agent_node:
    image: jenkins/agent
    volumes:
      - jenkins_home:/var/jenkins_home  
      - ${PROJECT_ROOT_DIR}:/var/jenkins_home/agent 
    environment:
      JENKINS_URL: http://192.168.0.108:8080 
      JENKINS_SECRET: ${JENKINS_AGENT_SECRET}
      JENKINS_AGENT_NAME: "agent node"

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_network:
    driver: bridge
